language: php
sudo: required
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
#  - hhvm
  - nightly
before_script:
  - sudo apt-get -y install php5-cli php5-curl
  - php -r "printf('PHP %s', phpversion());"
  - php -m
  - phpunit --version
  - composer require phpunit/phpunit
  - find .
  - ./vendor/bin/phpunit --version
script:
  - ./vendor/bin/phpunit test/
